// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gym_Api.Infrastructure.Data;

#nullable disable

namespace gym_Api.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("gym_Api.Infrastructure.Data.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-01",
                            Url = "/videos/video-01.mp4"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-02",
                            Url = "/videos/video-02.mp4"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Times",
                            Duration = 30,
                            FileName = "video-03",
                            Url = "/videos/video-03.mp4"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-04",
                            Url = "/videos/video-04.mp4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Times",
                            Duration = 30,
                            FileName = "video-05",
                            Url = "/videos/video-05.mp4"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-06",
                            Url = "/videos/video-06.mp4"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-07",
                            Url = "/videos/video-07.mp4"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-08",
                            Url = "/videos/video-08.mp4"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-09",
                            Url = "/videos/video-09.mp4"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-10",
                            Url = "/videos/video-10.mp4"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-11",
                            Url = "/videos/video-11.mp4"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-12",
                            Url = "/videos/video-12.mp4"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-13",
                            Url = "/videos/video-13.mp4"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-14",
                            Url = "/videos/video-14.mp4"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-15",
                            Url = "/videos/video-15.mp4"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Seconds",
                            Duration = 30,
                            FileName = "video-16",
                            Url = "/videos/video-16.mp4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
